In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [13]:
data = pd.read_csv('D:\Data Science\Datasets\WA_Fn-UseC_-Telco-Customer-Churn.csv')

data.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4174,3285-UCQVC,Female,0,No,No,37,No,No phone service,DSL,No,...,No,Yes,No,No,Month-to-month,No,Credit card (automatic),28.60,973.55,Yes
5029,1848-LBZHY,Female,0,Yes,No,7,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),50.30,355.1,No
4810,1112-CUNAO,Female,1,No,No,15,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,No,Electronic check,89.85,1424.95,Yes
6628,9979-RGMZT,Female,0,No,No,7,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,One year,Yes,Mailed check,94.05,633.45,No
2327,0869-PAPRP,Female,1,Yes,No,26,Yes,No,Fiber optic,No,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),85.70,2067,No

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [15]:
data.drop('customerID', axis = 'columns', inplace = True)

In [16]:
data = data[data['TotalCharges'] != ' ']

In [17]:
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'])

In [20]:
numeric_col = [num_col for num_col in data.columns if data[num_col].dtype != 'O']
catergorical_col = [cat_col for cat_col in data.columns if data[cat_col].dtype == 'O']

print("Numerical Attributes :", numeric_col)
print("\n\nCategorical Attributes :", catergorical_col)

Numerical Attributes : ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']


Categorical Attributes : ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

In [69]:
label_encod_col = []
onehot_encod_col = []
for col in catergorical_col:
    if len(data[col].unique()) > 2:
        onehot_encod_col.append(col)
    else:
        label_encod_col.append(col)